### ISSUE TITLE
Link to the tutorial page

### ISSUE THREAD

**Issue by danielfakunle** [danielfakunle/simplecalc#2]
https://guides.github.com/features/pages/

**Comment by Nnadozie** [comment]
Okay. So on the main page https://guides.github.com/,
there's the Git Handbook tutorial: https://guides.github.com/introduction/git-handbook/
that's what you need, but for now I'll walk you through using the cmd rather than git desktop:
first Install git
https://git-scm.com/downloads

**Comment by Nnadozie** [comment]
@tosinfakunle please close this when you have finished the Git handbook tutorial.
